service: default
runtime: python38


basic_scaling:
    max_instances: 8
    idle_timeout: 10m

resources:
    cpu: 4
    memory_gb: 16
    disk_size_gb: 10

entrypoint: gunicorn -b 0.0.0.0:8080 main:server
